services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.build
    image: next-start-web:latest
    container_name: next-start-web
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web/:/app/apps/web
    networks:
      - app_network

  docs:
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile.build
    image: next-start-docs:latest
    container_name: next-start-docs
    expose:
      - 3001
    ports:
      - "3001:3001"
    volumes:
      - ./apps/docs/:/app/apps/docs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
